apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jch2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jch2
    app.kubernetes.io/part-of: tkrw-pr712-0075-0066-app
  name: devfile-sample-jch2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jch2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jch2
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-jch2@sha256:37ffa524784b94ab9b3078bd001e6ce449a246d20a5ddf182687b6846430f530
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
